// export const ORDER_ACTION_TYPES = {
//     ORDER_START:'order/ORDER_START',
//     GET_USER_ORDER_START:'ortder/GET_USER_ORDER_START',
//     ORDER_SUCCESS:'order/ORDER_SUCCESS',
//     ORDER_FAILED:'order/ORDER_FAILED'
// }
export const ORDER_ACTION_TYPES = {
    SAVE_ORDER_START:'order/ORDER_START',
    GET_USER_ORDER_START:'order/GET_USER_ORDER_START',
    SET_USER_HISTORY_ORDER:'order/SET_USER_HISTORY_ORDER',
}